In [46]:
!pip install pandas
!pip install numpy
!pip install seaborn
!pip install matplotlib
!pip install scikit-learn




[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [47]:
#IMPORTING THE LIBRARIES
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import naive_bayes

In [48]:
#LOADING THE DATASET
data=pd.read_csv(r"C:\Users\proni\Downloads\archive (1).zip")
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [49]:
#CHECKING FOR ANY MISSING VALUES
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [50]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [51]:
#DATAPREPROCESSING USING STANDARD SCALER
scaler=StandardScaler()

In [52]:
x=data.drop(['Outcome'],axis=1)
y=data["Outcome"]
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [53]:
#SPLITING THE DATA INTO TWO SETS 80 % IN TRAIN SET AND 20% IN TEST SET
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
564            0       91             80              0        0  32.4   
421            2       94             68             18       76  26.0   
308            0      128             68             19      180  30.5   
563            6       99             60             19       54  26.9   
496            5      110             68              0        0  26.0   
..           ...      ...            ...            ...      ...   ...   
52             5       88             66             21       23  24.4   
181            0      119             64             18       92  34.9   
659            3       80             82             31       70  34.2   
458           10      148             84             48      237  37.6   
238            9      164             84             21        0  30.8   

     DiabetesPedigreeFunction  Age  
564                     0.601   27  
421                     0.561   21  
308                     1.391   25  
563                     0.497   32  
496                     0.292   30  
..                        ...  ...  
52                      0.342   30  
181                     0.725   23  
659                     1.292   27  
458                     1.001   51  
238                     0.831   32  

[614 rows x 8 columns]

In [54]:
X_train
Y_train


564    0
421    0
308    1
563    0
496    0
      ..
52     0
181    0
659    1
458    1
238    1
Name: Outcome, Length: 614, dtype: int64

In [55]:
#SCALING THE DATA
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [56]:
#APPLYING ALGORITHMS AND FITTING 
rfc=RandomForestClassifier(n_estimators=200)
rfc.fit(X_train_scaled,Y_train)
y_pred1=rfc.predict(X_test_scaled)
print(y_pred1)

[1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 1 0 0
 0 1 0 1 1 1 1 1 0 0 1 0 1 0 1 1 1 0 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 0
 0 1 1 1 1 0]


In [57]:
print("Accuracy_Score =", format(metrics.accuracy_score(Y_test,y_pred1)))

Accuracy_Score = 0.7727272727272727


In [58]:
dt=DecisionTreeClassifier()
dt.fit(X_train_scaled,Y_train)
y_pred2=dt.predict(X_test_scaled)
print(y_pred2)

[1 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0
 1 0 0 1 0 0 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1
 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 1 1 1 0
 0 1 1 0 1 1]


In [59]:
print("Accuracy_Score =", format(metrics.accuracy_score(Y_test ,y_pred2)))

Accuracy_Score = 0.7012987012987013


In [60]:
NB=naive_bayes.GaussianNB()
NB.fit(X_train_scaled,Y_train)
y_pred3=NB.predict(X_test_scaled)
print(y_pred3)

[1 0 0 1 1 0 0 0 1 1 0 1 1 0 0 0 0 0 1 1 1 1 0 1 1 1 1 0 1 0 0 1 1 0 1 0 0
 0 1 0 1 1 1 1 1 0 0 1 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0 1 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 1 1 0 0
 0 1 1 1 0 0]


In [61]:
print("Accuracy_Score =", format(metrics.accuracy_score(Y_test ,y_pred3)))

Accuracy_Score = 0.7402597402597403


In [63]:
#CHECK FOR 500TH PATIENT
rfc.predict([[2,117,90,19,71,25.2,0.313,21]])

array([1], dtype=int64)

In [65]:
#CHECK FOR THE 764TH PATIENT
rfc.predict([[2,122,70,27,0,36.8,0.340,27]])

array([1], dtype=int64)

In [66]:
#CHECK FOR THE FOURTH PATIENT
rfc.predict([[0,137,40,35,168,43.1,2.228,33]])

array([0], dtype=int64)